# Generated by Django 4.1.7 on 2023-02-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=72)),
                ("location", models.CharField(max_length=72)),
                ("about", models.TextField()),
                (
                    "types",
                    models.CharField(
                        choices=[("IT", "Software IT"), ("Non IT", "Medical")],
                        max_length=100,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
