# Generated by Django 4.1.7 on 2023-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_company_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=150)),
                ("phone", models.IntegerField(max_length=10)),
                ("about", models.TextField()),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("Manager", "Company Manager"),
                            ("Developer", "Software Developer"),
                            ("Developer", "Hardware Developer"),
                            ("Doctor", "Heart Doctor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
