# Generated by Django 4.1.7 on 2023-02-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
